### ISSUE TITLE
Suggestion: When remaking this project use FLTK

### ISSUE THREAD

**Issue by Rexhunter99** [carnivores-cpe/c3dit#1]
Source: https://github.com/fltk/fltk
It's open source and free to use, cross-platform and does most of what is needed I believe.
Would be better than hand coding the Win32 & COM stuff and would let Linux users use the tool.

I think I also need to be added to this project, I can't edit or do anything in here like change labels and I'm the owner of C3Dit.

**Comment by tminard** [comment]
@Rexhunter99 done. LMK if that didn’t work

**Comment by Rexhunter99** [comment]
> @Rexhunter99 done. LMK if that didn’t work

That worked it seems, thanks!

**Comment by Rexhunter99** [comment]
I decided to stick with Win32 API for now.
