### ISSUE TITLE
[BUG] The ability to rename any Treeview elements

### ISSUE THREAD

**Issue by zerer4000** [carnivores-cpe/c3dit#11]
If an user tries to rename an animation (or sound) with a treeview element (that is not the intended animation/sound) selected beforehand, the selected element will end up being renamed. 
If it's an animation and it ends up having the name of a pre-existing one, they both become the same thing.

**Comment by Dinoguy1000** [comment]
From the description, there's two separate bugs here:
- renaming an animation or sound while a different treeview element is selected, causes the selected element to be renamed instead (is this limited to attempting to rename animations and sounds, or does it happen with any treeview element?)
- it is possible (though maybe only in select circumstances?) to rename a treeview item to have the same name as another treeview item of the same type

**Comment by Rexhunter99** [comment]
I'll have to double-check the `TreeViewControl`'s methods and styles, I may have to re-work how the Win32 Notifications work for it perhaps and just force selection to return to the editing element.

**Comment by zerer4000** [comment]
> is this limited to attempting to rename animations and sounds, or does it happen with any treeview element?

Any treeview element
