### ISSUE TITLE
[BUG] C3dit 1.6 texture importing problems

### ISSUE THREAD

**Issue by zerer4000** [carnivores-cpe/c3dit#14]
The imported texture's hue will change. 

In some cases the editor might even crash: it happens if you try to import a vanilla texture of an animal onto the vanilla model of the same creature. If the texture is modified, C3dit will just change its hue.

The bug is exclusive only to the 1.6 version of the editor, so feel free to remove this report if it has been fixed.

**Comment by Rexhunter99** [comment]
This bug is pending more testing before closure but tentatively I'll say it is fixed in the 1.7.0 pre-release.
