### ISSUE TITLE
[BUG] The inability to remove things

### ISSUE THREAD

**Issue by zerer4000** [carnivores-cpe/c3dit#16]
The "remove" button doesn't work at all. Re-opening the saved car file shows that nothing happens with the supposedly deleted animation. The bug is present in 1.5.1, 1.6 and 1.6.1.

**Comment by Rexhunter99** [comment]
This issue has been addressed in the current development build. The context menu "Remove" has been renamed "Delete" and now functions correctly.
Additionally, in the Sound Manager and Animation Manager dialogs, you can delete the respective resources there as well.
